site_name: 梅普露的魔大陆召唤之旅
theme: readthedocs

nav:
    - README.md

    - 异闻录:
        - anecdote/001.md
        - anecdote/002.md
        - anecdote/003.md
        - anecdote/004.md
        - anecdote/005.md
        - anecdote/006.md
        - anecdote/007.md
        - anecdote/008.md
        - anecdote/009.md
        - anecdote/010.md
        - anecdote/011.md
        - anecdote/012.md
        - anecdote/013.md
        - anecdote/014.md
        - anecdote/015.md
        - anecdote/016.md
        - anecdote/017.md
        - anecdote/018.md
        - anecdote/019.md

    - 以下是草稿:
        - anecdote/020.md
        - anecdote/021.md
        - anecdote/022.md

    - 附录:
        - appendix/characters.md
        - appendix/about.md
